### ISSUE TITLE
Дизайн личного кабинета пользователя

### ISSUE THREAD

**Issue by dyakovri** [profcomff/webapp-ui#100]
Сейчас отрисованный дизайн такой

![Image](https://github.com/profcomff/webapp-ui/assets/5656720/ae56303e-6a3b-4f12-af8d-f5c806e7feed)

Кажется, он перегружен ненужной информацией, а действительно полезного там ничего нет. Возможно, стоит проработать отдельно страницу пользователя, и отдельно страницу с информацией о пользователе

**Comment by dyakovri** [comment]
Точно будут поля:
- Фамилия и Имя
- Номер группы
- Кнопки добавления/уделания методов входа (войти с помощью Google/Yandex/Physics/LK MSU) – полный список на https://app.test.profcomff.com/auth/all
- Добавлениe/изменение Email и Пароля для входа
- Список групп, в которых состоит пользователь

**Comment by Arzangulyan** [comment]
Все редактирование пользовательских данных (включая фио, группу, почту, пароль и другое) я бы вынес в новую страницу. Как это обычно и сделано в соц. сетях. И просто добавил бы кнопку редактирования (карандашик) на страницу

**Comment by Arzangulyan** [comment]
Последняя версия в [Фигме](https://www.figma.com/file/gfvuDN9x7I7sFCJQ7b1bIz/%D0%A2%D0%B2%D0%BE%D0%B9-%D0%A4%D0%A4!?type=design&node-id=2063-2760&mode=design&t=BKlNCR1EFXprcLeI-4)


![Image](https://github.com/profcomff/webapp-ui/assets/15670678/8409bb3c-a118-4ccd-af5e-84fcb4f93d12)

![Image](https://github.com/profcomff/webapp-ui/assets/15670678/23eefaab-8618-4991-9d4f-7d962f05169f)

**Comment by Arzangulyan** [comment]
Статистику пока можно не добавлять, либо сверстать, но скрыть
