### ISSUE TITLE
Дизайн страниц, связанных с авторизацией

### ISSUE THREAD

**Issue by Arzangulyan** [profcomff/webapp-ui#154]
# ТЗ

## Страница входа в аккаунт
- поля ввода почты и пароля
- чипы входа через альтернативные методы входа
- кнопка "войти"
- кнопка "забыл пароль"
- кнопка "зарегистрироваться"
- добавить политику даже на страницу входа

## Страница регистрации
- Чипы регистрации через альтернативные методы входа
- Поля ввода юзердаты
    - Почта*
    - Пароль*
    - Повтор пароля* (красная надпись "несовпадение паролей" под строкой ввода)
- Кнопка "зарегистрироваться"
- Галочка для согласия с политикой обработки перс данных и ссылка / надпись про согласие
![Image](https://github.com/profcomff/webapp-ui/assets/15670678/19a4b007-06f7-4d26-98bd-13332e7b6e19)

## Страница визард (просит ввести недостающие данные в профиль)
- Поля ввода данных
    - Имя пользователя
- Кнопка "добавить"
- Кнопка "пропустить" или крестик для выхода
- *возможно будут еще другие поля, так что надо заложить возможность их добавления*
// страница открывается после каждого открытия приложения И перехода в профиль

## Страница "забыл пароль" (только для тех, кто залогинен по почте)
- Поле ввода: почта
- Кнопка "восстановить пароль"
- После нажатия на кнопку восстановления редирект на страницу входа (логина)
- На странице входа высвечивается тост или надпись под полями ввода "**на указанную почту отправлено письмо для восстановления доступа к аккаунту**"

to be designed (нужно продумать UX):
страницы с:
- просмотром и редактироанием методов входа
- сменой почты
- сменой пароля
- просмотром сессий
- выходом из аккаунта
- кнопка сброса кэша
_эти функции могут быть как в трех точках на странице профиля, так и на новой странице "настройки", которая уже будет в трех точках_

**Comment by Arzangulyan** [comment]
См. правки с Олей в Фигме

**Comment by Temmmmmo** [comment]
@Arzangulyan доделать страницу из раздела настроек

**Comment by Arzangulyan** [comment]
https://www.figma.com/file/gfvuDN9x7I7sFCJQ7b1bIz/%D0%A2%D0%B2%D0%BE%D0%B9-%D0%A4%D0%A4!?type=design&node-id=2590-1623&mode=design&t=1ZcgUrYgdBALst3U-4
