### ISSUE TITLE
Создать страницу подтверждения почты, смены почты, смены пароля

### ISSUE THREAD

**Issue by grigoriev-semyon** [profcomff/webapp-ui#187]
УРЛы:
`/auth/register/success?token=%`
`/auth/reset/email?token=%`
`/auth/reset/password?token=%`

**Comment by grigoriev-semyon** [comment]
Сейчас по крайней мере первой страницы нет, кидает 404
Надо понять каких страниц еще нет
Логика этих страниц простая - надо что то отобразить и при этом кинуть запрос на нужную ручку из auth-api

**Comment by Arzangulyan** [comment]
Это должна быть страница, которая редиректит тебя в ЛК с тост уведомление "Х сделано успешно"
