### ISSUE TITLE
Сделать экран-страницу пользователя

### ISSUE THREAD

**Issue by physphile** [profcomff/webapp-ui#47]
Linked: profcomff/webapp-ui#56, profcomff/webapp-ui#58 

Там 2 экрана:

- [x] [экран личного кабинета](https://www.figma.com/file/gfvuDN9x7I7sFCJQ7b1bIz/%D0%A2%D0%B2%D0%BE%D0%B9-%D0%A4%D0%A4!?type=design&node-id=2063-2760&mode=design&t=9Dk3c24B6m7jKVsp-4)
- [x] [экран редактирования личного кабинета](https://www.figma.com/file/gfvuDN9x7I7sFCJQ7b1bIz/%D0%A2%D0%B2%D0%BE%D0%B9-%D0%A4%D0%A4!?type=design&node-id=2490-1162&mode=design&t=9Dk3c24B6m7jKVsp-4)

Создать `ProfileView` и использовать в нем `AuthApi`

https://www.figma.com/file/gfvuDN9x7I7sFCJQ7b1bIz/%D0%A2%D0%B2%D0%BE%D0%B9-%D0%A4%D0%A4!?type=design&node-id=2063-2760&mode=design&t=9Dk3c24B6m7jKVsp-4

**Comment by physphile** [comment]
ждем юзер-дату на беке

**Comment by dyakovri** [comment]
Есть вот такое ишью https://github.com/profcomff/webapp-ui/issues/100

**Comment by Arzangulyan** [comment]
Экран готов #100

**Comment by Arzangulyan** [comment]
В ЛК выводим только основную инфу пока что:
ФИО
почта
Курс
Дата рождения
